# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Ensure terminal colors look correct inside Ghostty
set-option -sa terminal-features ',xterm-ghostty:RGB'
set -g default-terminal "screen-256color"

# Start window and pane numbering at 1, not 0 (easier to reach on keyboard)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# More intuitive split commands (| for vertical side-by-side, - for horizontal)
# These will also open the new pane in the same directory you are currently in
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Smart pane switching with awareness of Vim splits (vim-tmux-navigator)
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# Easy config reload shortcut
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded!"

# Cheat sheet
# Open new session with name
# tmux new -s [name]
# list sessions
# tmux ls
# Re-attach
# tmux attach -t [name]
# kill session
# tmux kill-session-t dev

# Prefix key: Ctrl + b
# Split panel vertically: Prefix, then |
# Split panel horizontally: Prefix, then -
# Switch panel: Prefix, then arrow
# Zoom a panel: Prefix, then z (Press it again to un-zoom)
# Detach a session: Prefix, then d
